title: Info UMMU Ternate
description: "Prodi Informatika UMMU Ternate (temp)"
url: "https://infoummu.github.io"
author:
  name: "Informatika UMMU"
  email: "infoummu@outlook.com"
  url: "https://infoummu.github.io/hacker-blog"

# Build settings
# baseurl: /info
baseurl: /
# Change this to your relative path (ex: /blog/), or leave just a /
#markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 
paginate_path: /page:num/
#port: 9005
# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
#gems:
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
# Custom variables
owner : "Informatika_UMMU"
year : "2018"
